language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python -m py.test ./CheckIO/Home/*; python -m py.test ./Project-Euler/python/*.py;python -m py.test ./CheckIO/Elementary/*;python -m py.test ./CheckIO/Home/*; python -m py.test ./Project-Euler/python/*.py;python -m py.test ./CheckIO/Dropbox/*;python -m py.test ./CheckIO/Home/*; python -m py.test ./Project-Euler/python/*.py;python -m py.test ./CheckIO/Home/*;python -m py.test ./CheckIO/Home/*; python -m py.test ./Project-Euler/python/*.py;python -m py.test ./CheckIO/Oreilly/*;python -m py.test ./CheckIO/Home/*; python -m py.test ./Project-Euler/python/*.py;python -m py.test ./CheckIO/Scientific_Expedition/*;python -m py.test ./Coding_Bat/Warmup_1/*
before_install:
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install coveralls
after_success:
  - codecov
  - if [[ $ENV == python=3.5* ]]; then
          coveralls;
    fi