language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
- pip install codecov
# command to run tests
script: python -m py.test ./CheckIO/Home/*; python -m py.test ./Project-Euler/python/*.py;python -m py.test ./CheckIO/Elementary/*
after_success:
  - codecov --token=CodeCovKey

