language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
install:
    - make build

script:
    - echo "TODO"

#language: groovy
